// ═══════════════════════════════════════════════════════════════════
// SonoPrep — Study Notes (SERVER-SIDE ONLY)
// 15 sections, 43 premium cards with formulas and tables
// DO NOT IMPORT THIS FILE IN CLIENT COMPONENTS
// ═══════════════════════════════════════════════════════════════════

export interface Formula {
  title: string;
  formula: string;
  explanation: string;
}

export interface ComparisonTable {
  headers: string[];
  rows: string[][];
}

export interface StudyCard {
  title: string;
  subtitle: string;
  bullets: string[];
  formulas: Formula[];
  tables: ComparisonTable[];
}

export interface StudySection {
  id: number;
  title: string;
  cards: StudyCard[];
}

/** All 15 study note sections — SERVER USE ONLY */
export const STUDY_SECTIONS: StudySection[] = [
  { id: 1, title: `Sound Physics Fundamentals`, cards: [
    { title: `Nature of Sound Waves`, subtitle: `Understanding wave mechanics in ultrasound`, bullets: [`Sound is a mechanical vibration that travels through a medium as a longitudinal wave`, `Sound waves require a medium for propagation and cannot travel through a vacuum`, `The speed of sound varies depending on the medium's density and elasticity`, `In soft tissue, sound travels at approximately 1540 m/s`, `Sound waves consist of compressions (high pressure) and rarefactions (low pressure)`, `Frequency is the number of cycles per second, measured in Hertz (Hz)`, `Period is the time for one complete cycle, measured in seconds`, `Wavelength is the distance of one complete cycle, measured in millimeters`, `Amplitude is the maximum displacement from equilibrium, related to signal strength`, `Power is the rate of energy transfer, measured in Watts`], formulas: [], tables: [] },
    { title: `Relationship Between Frequency and Wavelength`, subtitle: `The fundamental wave equation`, bullets: [`Period = 1/frequency (T = 1/f)`, `Higher frequency transducers produce shorter wavelengths`, `Shorter wavelengths provide better resolution but less penetration`, `Lower frequency transducers penetrate deeper but with reduced resolution`, `Clinical frequencies range from 2 MHz to 15 MHz`, `Pulse repetition frequency (PRF) determines imaging depth capability`], formulas: [{ title: `Wave Equation`, formula: `Propagation Speed (c) = Frequency (f) × Wavelength (λ)`, explanation: `Since propagation speed is relatively constant in soft tissue (1540 m/s), frequency and wavelength are inversely related. 
              Higher frequency means shorter wavelength, and vice versa. This relationship is fundamental to transducer design and image quality.` }], tables: [] },
    { title: `Attenuation`, subtitle: `Signal loss during propagation`, bullets: [`Attenuation is the gradual decrease in sound wave intensity as it travels through tissue`, `Three main mechanisms: absorption, reflection, and scattering`, `Absorption converts sound energy to heat (major contributor)`, `Reflection occurs at tissue interfaces with different acoustic impedances`, `Scattering causes echoes to travel in multiple directions`, `Attenuation increases with frequency (approximately linear relationship)`, `Higher frequency ultrasound has greater attenuation and less penetration`, `Bone attenuates sound much more than soft tissue`, `Fluid attenuates sound minimally (good acoustic window)`, `Air causes nearly complete reflection (poor acoustic window)`], formulas: [{ title: `Attenuation Equation`, formula: `Intensity = I₀ × 10^(-α × d/10)`, explanation: `Where I is final intensity, I₀ is initial intensity, α is attenuation coefficient (dB/cm/MHz), 
              and d is depth in cm. The attenuation coefficient for soft tissue is approximately 0.5 dB/cm/MHz.` }], tables: [] }
  ] },
  { id: 2, title: `Pulse-Echo Imaging`, cards: [
    { title: `Pulse-Echo Principles`, subtitle: `How ultrasound imaging works`, bullets: [`Transducer emits short pulses of ultrasound energy into the body`, `Sound waves travel through tissue at 1540 m/s`, `Echoes are generated at tissue interfaces where acoustic impedance changes`, `The time for echo return determines reflector depth`, `The amplitude of the returning echo determines brightness`, `Pulse repetition period (PRP) is the time between pulse transmissions`, `Pulse repetition frequency (PRF) is the number of pulses per second`, `Maximum imaging depth is determined by PRP and propagation speed`], formulas: [{ title: `Range Equation`, formula: `Depth (cm) = Time (μs) × 0.077 / 2`, explanation: `Since sound travels 1.54 mm/μs in tissue, the one-way distance per microsecond is 0.077 cm. 
              The factor of 2 accounts for the round-trip time of the pulse.` }], tables: [] },
    { title: `Axial and Lateral Resolution`, subtitle: `Image resolution fundamentals`, bullets: [`Axial resolution = 1/2 × spatial pulse length (SPL)`, `SPL = number of cycles × wavelength`, `Higher frequency improves axial resolution but reduces penetration`, `Lateral resolution is best at the focal zone`, `Focusing narrows the beam at a specific depth`, `Elevational resolution is determined by slice thickness`], formulas: [], tables: [{ headers: ["Parameter", "Axial Resolution", "Lateral Resolution"], rows: [[`Definition`, `Ability to distinguish structures along the beam axis`, `Ability to distinguish structures perpendicular to beam axis`], [`Determined by`, `Wavelength and pulse length`, `Beam width`], [`Improving factors`, `Higher frequency, shorter pulses`, `Narrower beam, optimal focusing`], [`Typical range`, `0.1-1.0 mm`, `1.0-2.0 mm`]] }] },
    { title: `Time-Gain Compensation (TGC)`, subtitle: `Depth-dependent amplification`, bullets: [`TGC compensates for attenuation at different depths`, `Deeper structures require more gain compensation`, `Correct TGC produces uniform brightness throughout the image`, `Overcompensation appears as excessive brightness at depth`, `Undercompensation appears as fading at depth`, `TGC curves are adjusted using slide controls on the console`, `Modern systems may use automatic optimization`], formulas: [], tables: [] }
  ] },
  { id: 3, title: `Transducer Technology`, cards: [
    { title: `Piezoelectric Effect`, subtitle: `Transducer operation principles`, bullets: [`Piezoelectric crystals convert electrical energy to sound and vice versa`, `Lead zirconate titanate (PZT) is the most common crystal material`, `Reverse piezoelectric effect: electrical voltage causes crystal vibration`, `Forward piezoelectric effect: sound pressure causes electrical voltage`, `Crystal thickness determines resonant frequency`, `Resonant frequency f = c/(2×thickness) for PZT in ultrasound`, `Damping material reduces pulse duration and improves axial resolution`, `Higher damping reduces sensitivity but improves resolution`], formulas: [], tables: [] },
    { title: `Transducer Types`, subtitle: `Array configurations and applications`, bullets: [], formulas: [], tables: [{ headers: ["Transducer Type", "Beam Pattern", "Frequency Range", "Clinical Application"], rows: [[`Linear`, `Parallel, rectangular`, `5-15 MHz`, `Superficial structures, vascular`], [`Curvilinear`, `Divergent, trapezoidal`, `2-8 MHz`, `Abdomen, obstetrics`], [`Phased Array`, `Steered, sector`, `1-5 MHz`, `Cardiac, transcranial`], [`Endocavitary`, `Focused, small footprint`, `5-10 MHz`, `Transvaginal, transrectal`], [`Intracavitary`, `Highly focused`, `6-12 MHz`, `Intravascular, surgical`]] }] },
    { title: `Beam Formation`, subtitle: `Electronic beam steering and focusing`, bullets: [`Array transducers use multiple elements for electronic beam control`, `Beam steering: changing the angle of sound beam transmission`, `Beam focusing: concentrating energy at specific depths`, `Dynamic aperture: adjusting aperture size with depth`, `Dynamic focusing: adjusting focus zone in real-time`, `Phased array uses small elements with complex timing`, `Linear array uses sequential firing for parallel beams`, `Grating lobes are unwanted beams that cause artifacts`, `Apodization reduces side lobes but may reduce sensitivity`], formulas: [], tables: [] }
  ] },
  { id: 4, title: `Hemodynamics - Blood Flow Physics`, cards: [
    { title: `Blood Flow Characteristics`, subtitle: `Types of flow patterns`, bullets: [`Reynolds number predicts turbulence (critical value >2000)`, `High velocity + large diameter = turbulent flow risk`], formulas: [], tables: [{ headers: ["Flow Type", "Location", "Characteristics"], rows: [[`Laminar`, `Normal arteries`, `Parallel streamlines, faster in center, slower at walls`], [`Turbulent`, `Stenoses, valvular disease`, `Chaotic flow, eddies, mixed velocities`], [`Pulsatile`, `Arteries`, `Velocity varies with cardiac cycle`], [`Phasic`, `Veins`, `Velocity varies with respiration`], [`Steady`, `Central veins`, `Constant velocity`]] }] },
    { title: `Energy in Blood Flow`, subtitle: `Hemodynamic principles`, bullets: [`Blood flows from high energy to low energy regions`, `Three forms of energy: kinetic, pressure, gravitational`, `Kinetic energy: related to velocity (½mv²)`, `Pressure energy: potential energy from cardiac contraction`, `Gravitational energy: related to height above/below heart`, `Total energy is conserved in steady flow (Bernoulli's principle)`, `Energy losses occur through viscosity and turbulence`, `Higher hematocrit increases viscosity and energy loss`], formulas: [{ title: `Bernoulli's Principle`, formula: `ΔP = 4v² (simplified for valvular stenosis)`, explanation: `Pressure gradient equals 4 times the squared peak velocity. This simplified equation is used 
              to estimate pressure gradients across stenotic heart valves using Doppler ultrasound.` }], tables: [] }
  ] },
  { id: 5, title: `Doppler Ultrasound`, cards: [
    { title: `Doppler Effect`, subtitle: `Frequency shift in moving reflectors`, bullets: [`Doppler effect: frequency change when sound reflects off moving objects`, `Red blood cells act as moving reflectors`, `Frequency increases when blood moves toward transducer`, `Frequency decreases when blood moves away from transducer`, `Doppler shift is proportional to blood velocity`, `Clinical Doppler frequencies: 2-10 MHz`, `Doppler shift range: 20 Hz - 20 kHz (audible)`], formulas: [{ title: `Doppler Equation`, formula: `Δf = (2 × v × f₀ × cosθ) / c`, explanation: `Where Δf is Doppler shift, v is velocity, f₀ is transmitted frequency, θ is Doppler angle, 
              and c is propagation speed. The factor of 2 accounts for round-trip path. Maximum shift 
              occurs when θ = 0° (flow toward transducer). Zero shift when θ = 90°.` }], tables: [] },
    { title: `Spectral Doppler`, subtitle: `Pulsed wave vs continuous wave`, bullets: [], formulas: [], tables: [{ headers: ["Feature", "Pulsed Wave Doppler", "Continuous Wave Doppler"], rows: [[`Crystals`, `1 (alternates transmit/receive)`, `2 (separate transmit/receive)`], [`Range resolution`, `Yes - can localize depth`, `No - range ambiguity`], [`Maximum velocity`, `Limited by Nyquist limit`, `Unlimited`], [`Aliasing`, `Yes`, `No`], [`Clinical use`, `Carotid, peripheral, deep veins`, `Cardiac valvular stenosis`]] }] },
    { title: `Color Flow Doppler`, subtitle: `2D velocity mapping`, bullets: [`Color Doppler is a form of pulsed wave Doppler`, `Displays mean velocity encoded as color on 2D image`, `Red = flow toward transducer, Blue = flow away`, `Variance display shows turbulent flow (green component)`, `Color map converts velocities to colors using lookup table`, `Aliasing appears as color reversal (red to blue)`, `Multiple pulses per sample (packet) for accuracy`, `Larger packets = better accuracy but lower frame rate`], formulas: [], tables: [] },
    { title: `Power Doppler`, subtitle: `Amplitude-based flow detection`, bullets: [`Power Doppler displays amplitude of Doppler signal, not velocity`, `Non-directional - no information about flow direction`, `More sensitive to slow flow than color Doppler`, `No aliasing (no velocity scale)`, `Angle independent (except at exactly 90°)`, `Also called Energy Doppler or Color Angio`, `Disadvantages: no velocity info, lower frame rate, motion artifacts`, `Flash artifact can occur from transducer or patient motion`], formulas: [], tables: [] }
  ] },
  { id: 6, title: `Display Modes and Imaging`, cards: [
    { title: `A-Mode, B-Mode, M-Mode`, subtitle: `Basic display modes`, bullets: [`A-mode: first ultrasound display mode (amplitude)`, `B-mode: grayscale image from brightness of echoes`, `M-mode: motion display, high temporal resolution`, `M-mode is useful for measuring cardiac chamber sizes`, `Frame rate affects temporal resolution`, `Higher frame rates improve temporal resolution`], formulas: [], tables: [{ headers: ["Mode", "Display", "Information", "Clinical Use"], rows: [[`A-Mode`, `Amplitude vs depth`, `Reflector depth and intensity`, `Ophthalmology (historical)`], [`B-Mode`, `Brightness vs position`, `2D anatomical image`, `All general imaging`], [`M-Mode`, `Motion vs time`, `Depth-time plot of motion`, `Cardiac, fetal heart`]] }] },
    { title: `3D/4D Imaging`, subtitle: `Volume imaging`, bullets: [`3D imaging uses 2D array transducers with thousands of elements`, `Rendering creates photo-like images with shadows and texture`, `4D imaging is real-time 3D imaging`, `Common in obstetrics for fetal anatomy assessment`, `Used in echocardiography for cardiac assessment`, `Surface rendering, maximum intensity, and transparent modes available`], formulas: [], tables: [] }
  ] },
  { id: 7, title: `Image Artifacts`, cards: [
    { title: `Artifact Recognition`, subtitle: `Common artifacts and their causes`, bullets: [], formulas: [], tables: [{ headers: ["Artifact", "Appearance", "Cause", "Assumption Violated"], rows: [[`Shadowing`, `Anechoic region behind structure`, `High attenuation`, `Attenuation is uniform`], [`Enhancement`, `Hyperechoic region behind structure`, `Low attenuation`, `Attenuation is uniform`], [`Reverberation`, `Parallel echoes at increasing depth`, `Multiple reflections between surfaces`, `Single reflection path`], [`Comet tail`, `Short, dense reverberation`, `Closely spaced reflectors`, `Single reflection path`], [`Mirror image`, `Duplication of structure`, `Reflection off strong reflector`, `Straight line travel`], [`Speed error`, `Mispositioned structures`, `Incorrect propagation speed assumed`, `1540 m/s in all tissue`], [`Side lobes`, `Ghost echoes off axis`, `Off-axis beam energy`, `Beam is only along main axis`], [`Grating lobes`, `Ghost echoes from array transducers`, `Off-axis energy from elements`, `Beam is only along main axis`]] }] },
    { title: `Resolution Artifacts`, subtitle: `Axial and lateral resolution limitations`, bullets: [`Axial resolution artifact: structures closer than axial resolution appear as one`, `Lateral resolution artifact: structures at same depth appear as one if within beam width`, `Slice thickness artifact: structures outside imaging plane appear in image`, `Range resolution: ability to distinguish structures along beam axis`, `Azimuthal resolution: lateral resolution in scan plane`, `Elevational resolution: slice thickness perpendicular to scan plane`], formulas: [], tables: [] }
  ] },
  { id: 8, title: `Digital Image Processing`, cards: [
    { title: `Digital Image Fundamentals`, subtitle: `Pixels and grayscale`, bullets: [`Digital images divided into small squares called pixels`, `Each pixel assigned a number representing echo amplitude`, `Brighter echo = higher number`, `Ultrasound images typically 512 × 512 pixels (262,144 pixels)`, `Bits per pixel determines number of grayscale levels`, `4 bits = 16 shades, 8 bits = 256 shades`, `Most systems use 8-bit grayscale (256 levels)`], formulas: [], tables: [] },
    { title: `Pre-Processing vs Post-Processing`, subtitle: `When adjustments are applied`, bullets: [], formulas: [], tables: [{ headers: ["Pre-Processing", "Post-Processing"], rows: [[`Adjustments before A/D conversion`, `Adjustments after A/D conversion`], [`Changes affect the actual signal`, `Changes affect the displayed image only`], [`Cannot be changed after acquisition`, `Can be adjusted after acquisition`], [`Examples: TGC, output power`, `Examples: contrast, brightness, gamma`]] }] },
    { title: `Dynamic Range`, subtitle: `Grayscale range control`, bullets: [`Dynamic range: range of signal amplitudes displayed`, `Measured in decibels (dB)`, `Narrow dynamic range = high contrast image (fewer grays)`, `Wide dynamic range = low contrast image (more grays)`, `Optimal dynamic range balances detail and contrast`, `Modern systems typically use 60-80 dB`], formulas: [], tables: [] }
  ] },
  { id: 9, title: `Image Enhancement Techniques`, cards: [
    { title: `Harmonic Imaging`, subtitle: `Non-linear tissue response`, bullets: [`Harmonic imaging uses frequencies twice the fundamental`, `Tissue harmonics are created during propagation (not at transducer)`, `Harmonic signals increase with depth`, `Improves signal-to-noise ratio`, `Reduces near-field artifacts and side lobes`, `Beneficial for difficult-to-image patients`, `Lower frame rate due to pulse inversion technique`], formulas: [{ title: `Harmonic Frequency`, formula: `f_harmonic = 2 × f_fundamental`, explanation: `The second harmonic is twice the transmitted frequency. Higher harmonics (3×, 4×) exist 
              but are weaker. Tissue harmonic imaging typically receives at 2× the transmitted frequency.` }], tables: [] },
    { title: `Spatial Compounding`, subtitle: `Multiple angle imaging`, bullets: [`Technique for producing single image from several angles`, `Frames are overlapped to form single real-time image`, `Reduces speckle and noise`, `Improves contrast resolution`, `Reduces certain artifacts (anisotropy, shadowing)`, `May reduce lateral resolution`, `Frame rate reduced due to multiple acquisitions`], formulas: [], tables: [] },
    { title: `Temporal Compounding`, subtitle: `Frame averaging`, bullets: [`Also called persistence or temporal averaging`, `Superimposes current frame on previous frames`, `Creates smoother image with reduced noise`, `Different from spatial compounding (uses identical views)`, `May reduce temporal resolution`, `Motion artifacts may appear as smearing`], formulas: [], tables: [] },
    { title: `Coded Excitation`, subtitle: `Enhanced pulse transmission`, bullets: [`Creates very long sound pulses with wide frequency range`, `Strong pulse with peak intensity below FDA limits`, `Higher signal-to-noise ratio`, `Improves axial, spatial, and contrast resolution`, `Provides deeper penetration`, `Maintains safety while improving image quality`], formulas: [], tables: [] },
    { title: `Contrast Agents`, subtitle: `Microbubble enhancement`, bullets: [`Small gas bubbles called microbubbles enhance echo signals`, `Encapsulated in shell for stability`, `Used intravenously or by ingestion`, `Power must be reduced to prevent bubble rupture`, `Requirements: safe, metabolically inert, long-lasting, small size`, `Microbubbles have nonlinear behavior (resonance)`, `Contrast harmonics are stronger than tissue harmonics`, `Mechanical index controls harmonic production`], formulas: [], tables: [{ headers: ["Feature", "Tissue Harmonics", "Contrast Harmonics"], rows: [[`Creation`, `In tissue during propagation`, `Off microbubbles during reflection`], [`Presence`, `Always present`, `Only with contrast agents`], [`Signal strength`, `Weaker`, `Stronger`], [`MI threshold`, `All MI levels`, `MI > 0.1`]] }] }
  ] },
  { id: 10, title: `Doppler Artifacts and Optimization`, cards: [
    { title: `Doppler Artifacts`, subtitle: `Common issues and solutions`, bullets: [`Aliasing: false appearance of reversed flow direction`, `Ghosting: color flashes from tissue motion (CFD) or clutter (spectral)`, `Mirror image: duplicate spectrum above/below baseline`, `Wall filter eliminates low-frequency Doppler shifts`, `High wall filter may eliminate slow flow signals`, `Excessive gain causes noise throughout spectrum`, `Insufficient gain causes loss of low-velocity signals`], formulas: [], tables: [] },
    { title: `Doppler Optimization`, subtitle: `Proper technique for accurate measurements`, bullets: [`Doppler angle must be 60° or less for accurate velocity measurement`, `Angle correction cursor must be parallel to flow direction`, `Sample volume should be placed in center of vessel for laminar flow`, `Wall filter setting affects low-velocity detection`, `Color gain should show color only within vessels`, `Spectral gain should be adjusted to eliminate noise`, `Scale setting appropriate for expected velocities`], formulas: [], tables: [] }
  ] },
  { id: 11, title: `Quality Assurance`, cards: [
    { title: `QA Program Components`, subtitle: `Ensuring optimal image quality`, bullets: [`Quality assurance is a medical and legal necessity`, `Objective standards provide measurable, consistent evaluation`, `Subjective standards vary between individuals`, `Daily operational checks include cables, transducers, and cleaning`, `Preventive maintenance includes annual calibration`, `Documentation of all maintenance and incidents required`, `Program should include: system assessment, preventive maintenance, repairs, record keeping`], formulas: [], tables: [] },
    { title: `Phantoms and Test Objects`, subtitle: `QA measurement tools`, bullets: [`Phantoms contain tissue-mimicking material (gel and graphite)`, `Propagation speed matches soft tissue (1540 m/s)`, `Stainless steel pins at various depths for identification`, `Cyst and mass mimics for contrast resolution testing`, `AIUM test object specifically designed for resolution measurement`], formulas: [], tables: [{ headers: ["Phantom Type", "Purpose", "What It Tests"], rows: [[`Tissue equivalent`, `General imaging performance`, `Grayscale, texture, sensitivity`], [`Beam profile`, `Slice thickness`, `Elevational resolution`], [`Doppler`, `Doppler accuracy`, `Velocity accuracy, sensitivity`], [`Flow phantom`, `Flow simulation`, `Doppler sensitivity, depth resolution`], [`AIUM test object`, `Resolution measurement`, `Axial, lateral, dead zone`]] }] },
    { title: `Performance Measurements`, subtitle: `Key QA parameters`, bullets: [`Sensitivity: ability to detect weak echoes`, `Uniformity: consistent image quality across field`, `Dead zone: region near transducer with unreliable imaging`, `Range accuracy: correct depth calibration`, `Lateral accuracy: correct horizontal positioning`, `Axial resolution: along beam axis resolution`, `Lateral resolution: perpendicular to beam resolution`, `Contrast resolution: ability to distinguish shades of gray`, `Elevational resolution: slice thickness`], formulas: [], tables: [] }
  ] },
  { id: 12, title: `Bioeffects and Safety`, cards: [
    { title: `Thermal Effects`, subtitle: `Tissue heating from ultrasound`, bullets: [`Thermal effects caused by attenuation (primarily absorption)`, `Absorption converts sound energy to heat`, `Temperature rise of 1°C is considered safe`, `Rise to 41°C or higher is hazardous, especially to fetus`, `Longer exposure at elevated temperature = more dangerous`, `Thermal index (TI) indicates potential temperature rise`, `Higher frequencies produce more heating (more absorption)`, `Focusing increases intensity at focal point`], formulas: [], tables: [] },
    { title: `Cavitation`, subtitle: `Bubble interaction effects`, bullets: [`Cavitation: interaction of sound with gas bubbles in tissue`, `Two types: stable and transient (inertial) cavitation`, `Stable: microbubbles expand and contract without bursting`, `Transient: microbubbles expand and violently collapse`, `Mechanical index (MI) relates to cavitation risk`, `Lower MI = less pressure = less cavitation risk`, `Higher MI = greater pressure = higher cavitation risk`, `ALARA principle should guide all ultrasound use`], formulas: [{ title: `Mechanical Index`, formula: `MI = Peak Rarefactional Pressure (MPa) / √Frequency (MHz)`, explanation: `MI indicates the likelihood of cavitation. Values below 0.7 are generally considered low risk.
              Values above 1.0 indicate higher cavitation potential.` }], tables: [] },
    { title: `ALARA Principle`, subtitle: `Safety-first approach`, bullets: [`ALARA = As Low As Reasonably Achievable`, `Minimize exposure time and intensity`, `Use lowest output power and highest gain possible`, `Limit Doppler use in early pregnancy`, `Keep thermal and mechanical indices low`, `No confirmed harmful effects at diagnostic levels`, `Prudent use still recommended`], formulas: [], tables: [] }
  ] },
  { id: 13, title: `Clinical Application and Patient Care`, cards: [
    { title: `Medical Ethics`, subtitle: `Core principles of patient care`, bullets: [`Informed consent includes: procedure nature, alternatives, risks/benefits`, `Patient may withdraw consent at any time`, `Sonographer must identify patient and describe procedure`, `Patient dignity and privacy must be maintained`, `Only physicians may interpret and diagnose results`], formulas: [], tables: [{ headers: ["Principle", "Description"], rows: [[`Autonomy`, `Respect patient self-determination; informed consent required`], [`Beneficence`, `Actions should benefit the patient`], [`Non-maleficence`, `Do no harm; treat patients safely`], [`Justice`, `Fairness in treatment and resource allocation`]] }] },
    { title: `Infection Control`, subtitle: `Standard precautions`, bullets: [`Standard precautions assume all patients are potentially infectious`, `Hand washing is the most important infection control measure`, `Appropriate PPE includes gloves, gowns, masks as needed`, `Sharps must be disposed in designated containers`, `Soiled linens require proper handling`, `OSHA regulates workplace safety`, `SDMS provides professional guidelines`], formulas: [], tables: [] },
    { title: `Ergonomics`, subtitle: `Preventing work-related injuries`, bullets: [`Ergonomics maximizes productivity while reducing operator fatigue`, `Repetitive motions, poor posture, and strain cause injuries`, `Keep arms close to body during scanning`, `Avoid bending; use proper sitting position`, `Use proper foot support`, `Hold probe with palm, not fingers`, `Ergonomic devices: wrist supports, adaptive cushions, proper equipment design`, `Education on proper techniques and exercise protocols is essential`], formulas: [], tables: [] }
  ] },
  { id: 14, title: `Diagnostic Testing and Statistics`, cards: [
    { title: `Test Outcomes`, subtitle: `True/false positive and negative`, bullets: [`True positive: disease present and test positive (correct)`, `True negative: disease absent and test negative (correct)`, `False positive: disease absent but test positive (incorrect)`, `False negative: disease present but test negative (incorrect)`], formulas: [], tables: [{ headers: ["Outcome", "Disease Present", "Disease Absent"], rows: [[`Test Positive`, `True Positive (TP)`, `False Positive (FP)`], [`Test Negative`, `False Negative (FN)`, `True Negative (TN)`]] }] },
    { title: `Sensitivity and Specificity`, subtitle: `Test accuracy measures`, bullets: [`Sensitivity: ability to identify disease when present (minimize false negatives)`, `High sensitivity = few false negatives`, `Specificity: ability to identify normal when disease absent (minimize false positives)`, `High specificity = few false positives`, `Sensitivity and specificity are inversely related`, `Trade-off exists between sensitivity and specificity`], formulas: [{ title: `Formulas`, formula: `Sensitivity = TP / (TP + FN) × 100%`, explanation: `` }], tables: [] },
    { title: `Predictive Values`, subtitle: `Probability of disease given test result`, bullets: [`Positive Predictive Value (PPV): probability of disease given positive test`, `Negative Predictive Value (NPV): probability of no disease given negative test`, `PPV and NPV depend on disease prevalence`, `Higher sensitivity = higher NPV`, `Higher specificity = higher PPV`], formulas: [{ title: `Predictive Value Formulas`, formula: `PPV = TP / (TP + FP) × 100%`, explanation: `` }], tables: [] }
  ] },
  { id: 15, title: `Additional Key Concepts for Exam Success`, cards: [
    { title: `Key Formulas Summary`, subtitle: `Essential equations for the SPI exam`, bullets: [], formulas: [], tables: [{ headers: ["Formula", "Application"], rows: [[`c = f × λ`, `Propagation speed calculation`], [`Depth = (Time × 1540) / 2`, `Range equation`], [`Δf = (2v × f₀ × cosθ) / c`, `Doppler shift equation`], [`Attenuation = α × f × d`, `Total attenuation`], [`Axial Resolution = SPL / 2`, `Axial resolution calculation`], [`PRF = c / (2 × depth)`, `Maximum PRF for depth`], [`Nyquist = PRF / 2`, `Maximum unambiguous velocity`], [`MI = Pressure / √f`, `Mechanical index`], [`TI = Output / Threshold`, `Thermal index`]] }] },
    { title: `Exam Preparation Tips`, subtitle: `Success strategies`, bullets: [`Understand the 6 imaging assumptions (the foundation of artifact recognition)`, `Know the relationship between frequency, resolution, and penetration`, `Master the Doppler equation and angle dependence`, `Understand aliasing causes and solutions`, `Know the difference between all display modes`, `Recognize all common artifacts by appearance and cause`, `Understand bioeffects: thermal and mechanical (cavitation)`, `Know ALARA principle and its practical application`, `Understand sensitivity, specificity, and predictive values`, `Be familiar with QA procedures and what each test measures`], formulas: [], tables: [] }
  ] }
];
